### ISSUE TITLE
ValueError: too many values to unpack (expected 2)

### ISSUE THREAD

**Issue by aaronlsmiles** [decadenza/SimpleStereo#11]
I'm running your [Basic example](https://github.com/decadenza/SimpleStereo#basic-example) with the path to images changed to my image folder, but keep getting the following error:

```
Traceback (most recent call last):
  File "000 CalibrateSingleCamera.py", line 19, in <module>
    rig = ss.calibration.chessboardStereo(images, chessboardSize=(7,6), squareSize=60.5)
  File "/home/xxx/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages/simplestereo/calibration.py", line 119, in chessboardStereo
    for path1, path2 in images:
ValueError: too many values to unpack (expected 2)
```

**Comment by decadenza** [comment]
Hi. Thanks for reporting this error. The readme was wrong.

If you are calibrating a **single** camera, you should use:
```
images = ["0.png","1.png","2.png",...]
...
ss.calibration.chessboardSingle(images, chessboardSize=(7,6), squareSize=60.5)
```

If you are calibrating a stereo system, instead:
```
images = [("oneL.png","oneR.png"), ("twoL.png","twoR.png"), ...]
...
ss.calibration.chessboardStereo(images, chessboardSize=(7,6), squareSize=60.5)
```

Corrected README with the single camera example.

**Comment by aaronlsmiles** [comment]
Great! The code runs and begins calibrating, but then throws this error now:

```
Traceback (most recent call last):
  File "000 CalibrateSingleCamera.py", line 22, in <module>
    rig.save("myRig.json")
AttributeError: 'tuple' object has no attribute 'save'
```

**Comment by aaronlsmiles** [comment]
> Great! The code runs and begins calibrating, but then throws this error now:
> 
> ```
> Traceback (most recent call last):
>   File "000 CalibrateSingleCamera.py", line 22, in <module>
>     rig.save("myRig.json")
> AttributeError: 'tuple' object has no attribute 'save'
> ```

Should I post this as a new issue?

**Comment by decadenza** [comment]
No need, but post the full code you are using. I cannot see where `rig` comes from.

**Comment by decadenza** [comment]
Well I can anticipate the problem. My bad. The basic example is wrong again. Calibrating a single camera, you cannot have a `stereoRig` object.

I will update it again. Please refer to the examples in the examples folder.

**Comment by aaronlsmiles** [comment]
That's ok as I don't need the `stereoRig` object--I am just trying to get the RPE of a single camera to compare it with the RPE of the stereo pair.

My code looks like this:

```
import simplestereo as ss
import os


# Paths
curPath = os.path.dirname(os.path.realpath(__file__))
loadPath = os.path.join(curPath,"res","4L","calib-10")    # Image folder

# Total number of images
N_IMAGES = 30

# Image paths
images = [ ( os.path.join(loadPath,str(i)+'_L.png')) for i in range(N_IMAGES) ]
print(f"Calibrating using {len(images)} images from:\n{loadPath}...")

# Calibrate and build StereoRig object
rig = ss.calibration.chessboardSingle(images, chessboardSize=(7,6), squareSize=27.0)

# Optionally print some info
print("Reprojection error:", rig.reprojectionError)
print("Centers:", rig.getCenters())
print("Baseline:", rig.getBaseline())
```

I removed the lines of code regarding the rig. So now the error I get is this:

```
Traceback (most recent call last):
  File "000 CalibrateSingleCamera.py", line 22, in <module>
    print("Reprojection error:", rig.reprojectionError)
AttributeError: 'tuple' object has no attribute 'reprojectionError'
```
