### ISSUE TITLE
`Build3DPointCloud` error: !ssize.empty() in function 'remapBilinear'

### ISSUE THREAD

**Issue by aaronlsmiles** [decadenza/SimpleStereo#19]
I've successfully completed the `RectifyRig`, which rectifies the images fine and both `StereoMatchingSGBM` and `StereoMatchingASW` work fine too. But when I run `Build3DPointCloud` I get the following error:

```
(venv) xxxx@ubuntu:~/PycharmProjects/pythonProject/SimpleStereo-master/examples$ python3 "011 Build3DPointCloud.py"
011 Build3DPointCloud.py:14: DeprecationWarning: Please use `wiener` from the `scipy.signal` namespace, the `scipy.signal.signaltools` namespace is deprecated.
  from scipy.signal.signaltools import wiener
Traceback (most recent call last):
  File "011 Build3DPointCloud.py", line 38, in <module>
    img1_rect, img2_rect = rigRect.rectifyImages(img1, img2)
  File "/home/xxxx/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages/simplestereo/__init__.py", line 497, in rectifyImages
    img1_rect = cv2.remap(img1, self.mapx1, self.mapy1, interpolation);
cv2.error: OpenCV(4.5.2) /tmp/pip-req-build-sl2aelck/opencv/modules/imgproc/src/imgwarp.cpp:668: error: (-215:Assertion failed) !ssize.empty() in function 'remapBilinear'
```

The output should be the 3D point cloud and rectified images, as it does with the provided inputs, but it doesn't seem to like the images I have (resolution is (3840, 2160)).

**Comment by decadenza** [comment]
The problem seems to be on image rectification on line 38 but I cannot test without a minimum reproducible code, the rig and the images.
Are the image path correct? Are you able to show them before line 38 maybe using `cv2.imshow()`?

**Comment by aaronlsmiles** [comment]
It won't reproduce for me now. Loaded the venv back up and works fine now. Made absolutely no changes since, so no idea what was causing the issue in first place! Will keep an eye on it to see if it happens again, but I'll close this issue.

**Comment by aaronlsmiles** [comment]
It won't reproduce for me now. Loaded the venv back up and works fine now. Made absolutely no changes since, so no idea what was causing the issue in first place! Will keep an eye on it to see if it happens again, but I'll close this issue.

**Comment by aaronlsmiles** [comment]
It won't reproduce for me now. Loaded the venv back up and works fine now. Made absolutely no changes since, so no idea what was causing the issue in first place! Will keep an eye on it to see if it happens again, but I'll close this issue.
