### ISSUE TITLE
Installation via pip3: numpy headers not found

### ISSUE THREAD

**Issue by KevinCain** [decadenza/SimpleStereo#2]
First, warm regards and real thanks for this promising project, which is well designed to fill a longstanding hole in stereo. I would have loved such an elegant approach when I began working in structured light ten years ago.

Turning to installation via pip-22.0.3, `pip install .` yields the following compiler error for a numpy header:

```
./simplestereo/_passive.cpp:4:10: fatal error: numpy/arrayobject.h: No such file or directory
4 | #include <numpy/arrayobject.h>
```
I can import numpy into python 3.9.7 without trouble, and pip reports finding numpy 1.20.3 during the SimpleStereo setup:

`Requirement already satisfied: numpy>=1.19 in /home/kevin/anaconda3/lib/python3.9/site-packages (from SimpleStereo==0.9.0) (1.20.3)`

Conda, likewise, shows numpy is installed and available in the base conda environment (where I am installing SimpleStereo):

```
conda install numpy
Collecting package metadata (current_repodata.json): done
Solving environment: done
# All requested packages already installed.
```

**Comment by decadenza** [comment]
Hi and thank you for your comment.
Happy that my code can be useful.

It seems that `numpy` headers are not found.
On what OS are you working? 

We should try the solution suggested [here](https://stackoverflow.com/questions/14657375/cython-fatal-error-numpy-arrayobject-h-no-such-file-or-directory) 

and add
`include_dirs=[numpy.get_include()]` for each external module in `setup.py`

Could you please try that in the meantime?
Thanks.

**Comment by decadenza** [comment]
Fixed setup.py following your report.
Now numpy headers are automatically included.
