### ISSUE TITLE
003 BuildStereoRig.py No run

### ISSUE THREAD

**Issue by felipe8066** [decadenza/SimpleStereo#23]
I have an error when run 003 BuildStereoRig.py.  My left image i capture with go pro Hero 3 and rigth with hero 4, the image have same resolution but no run, the error menssage is:

Traceback (most recent call last):
  File "003 BuildStereoRig.py", line 24, in <module>
    rig = ss.calibration.chessboardStereo( images, chessboardSize=(6,4), squareSize=60.5 )
  File "/home/pablo_vergara/.local/lib/python3.8/site-packages/simplestereo/calibration.py", line 156, in chessboardStereo
    retval, intrinsic1, distCoeffs1, intrinsic2, distCoeffs2, R, T, E, F = cv2.stereoCalibrate( np.array([[objp]] * counter), imagePoints1, imagePoints2, cameraMatrix1, distCoeffs1, cameraMatrix2, distCoeffs2, imageSize = img1.shape[::-1], flags=flags, criteria = DEFAULT_TERMINATION_CRITERIA)
cv2.error: OpenCV(4.5.2) /tmp/pip-req-build-sl2aelck/opencv/modules/calib3d/src/calibration.cpp:3338: error: (-215:Assertion failed) nimages > 0 in function 'collectCalibrationData'
![GOPR1870](https://github.com/decadenza/SimpleStereo/assets/111525276/653115ef-5fd8-4f82-af0f-70ac6224a27c)
![GOPR5723](https://github.com/decadenza/SimpleStereo/assets/111525276/d36b49b8-01c6-41a2-a8d9-33fc3a6bb8d5)
/
Any idea for solution?
thank

**Comment by decadenza** [comment]
Would you please post the code you are using?
I assume you have several couples of left and right images in the folder, not just these 2, right?
