### ISSUE TITLE
Is this a typo?

### ISSUE THREAD

**Issue by KevinCain** [decadenza/SimpleStereo#24]
In https://github.com/decadenza/SimpleStereo/blob/05897e4279fe997c32f381e4cf89c0bbf0829bd9/simplestereo/_rigs.py#L80C5-L80C23 we see:
 
```
    @intrinsic1.setter
    def intrinsic2(self, v):
        self._intrinsic2 = np.asarray(v) # Ensure numpy.ndarray.
```

Shouldn't this instead be 'intrinsic2' as below?

```
    @intrinsic2.setter
    def intrinsic2(self, v):
        self._intrinsic2 = np.asarray(v) # Ensure numpy.ndarray.
```

**Comment by decadenza** [comment]
Definitely a typo! Well spotted. Committing now on master branch.
