### ISSUE TITLE
Converting SS Stereo Rig data to Middlebury calibration format

### ISSUE THREAD

**Issue by KevinCain** [decadenza/SimpleStereo#26]
I'm converting from the 'rig.json' output by SS to the Middlebury stereo calibration format, e.g:

> cam0=[4161.221 0 1445.577; 0 4161.221 984.686; 0 0 1]
> cam1=[4161.221 0 1654.636; 0 4161.221 984.686; 0 0 1]
> doffs=209.059
> baseline=176.252
> width=2880
> height=1988
> ndisp=280
> isint=0
> vmin=25
> vmax=248
> dyavg=0
> dymax=0

I'm adapting as follows:
_intrinsics: Directly copied from intrinsic1 and intrinsic2
baseline: The magnitude of the translation vector T
width & height: taken from res1 or res2
doffs (Disparity Offset): Difference in the x coordinates of the principal points; doffs = ∣cx1​−cx2​∣_

Using the sample 'rig.json' (see below), calculating using the above gives:
**doffs: 3.8929
baseline: 79.6935**

Questions:
- Should I instead use the rectified rig output 'rigRect.json'?
- Anything I am plainly wrong about above?
- Do you already have a helper method which I'm overlooking?

Here's a sample rig.json I compute the above from:

> {
>     "res1": [
>         1016,
>         1016
>     ],
>     "res2": [
>         1016,
>         1016
>     ],
>     "intrinsic1": [
>         [
>             579.2446179977145,
>             0.0,
>             502.3987796882491
>         ],
>         [
>             0.0,
>             579.5116671220319,
>             510.58215499440627
>         ],
>         [
>             0.0,
>             0.0,
>             1.0
>         ]
>     ],
>     "intrinsic2": [
>         [
>             579.7032272217316,
>             0.0,
>             506.2916650154022
>         ],
>         [
>             0.0,
>             579.0288750228291,
>             506.2326237927359
>         ],
>         [
>             0.0,
>             0.0,
>             1.0
>         ]
>     ],
>     "R": [
>         [
>             0.767966363180443,
>             0.2848130094378503,
>             -0.5736804116216266
>         ],
>         [
>             -0.13848577098642145,
>             0.948340505844807,
>             0.2854329627220935
>         ],
>         [
>             0.6253393928561516,
>             -0.13975634021027653,
>             0.7677361585293018
>         ]
>     ],
>     "T": [
>         [
>             -73.19133048127482
>         ],
>         [
>             30.43887113892361
>         ],
>         [
>             -8.219245016166784
>         ]
>     ],
>     "distCoeffs1": [
>         -0.22860155177247918,
>         0.03470845492312883,
>         0.0004766461903491566,
>         0.0005281749453998419,
>         0.002510718878933444
>     ],
>     "distCoeffs2": [
>         -0.22843877922351902,
>         0.03427693912719873,
>         -0.0007867481118159982,
>         0.0010394683535731879,
>         0.0035491311754853273
>     ],
>     "F": [
>         [
>             1.4152886509291195e-06,
>             2.798715649599464e-07,
>             0.0003240205945820065
>         ],
>         [
>             3.124014022836698e-06,
>             -9.947571448141776e-07,
>             0.00173167854548996
>         ],
>         [
>             -0.002905008861574782,
>             -0.003215979681710672,
>             1.0
>         ]
>     ],
>     "E": [
>         [
>             17.896376714250966,
>             3.540617745785841,
>             25.715065454468935
>         ],
>         [
>             39.45731846233975,
>             -12.569900391545339,
>             60.90685076543608
>         ],
>         [
>             -13.240071336656001,
>             -78.07968986503437,
>             -3.429034180566795
>         ]
>     ],
>     "reprojectionError": 0.1276660221803029,
>     "fisheye1": false,
>     "fisheye2": false
> }

**Comment by decadenza** [comment]
> Should I instead use the rectified rig output 'rigRect.json'?

The rectified rig container all the information from 'rig.json', plus the homographies and common orientation data. So, if you need rectification information you should copy those too (or you need to rectify your images with some other algorithm). I suggest you still use `ss.rectification.directRectify` for rectification. We have been through [a lot of geometry stuff](https://arxiv.org/pdf/2203.00123.pdf).

> Anything I am plainly wrong about above?

Your reasoning is fine. You can check that the baseline measure is _roughly_ the distance of the two cameras. The number 79.6935 would be in the same unit you used for the square side of the chessboard.

> Do you already have a helper method which I'm overlooking?

You can check the [`StereoRig` class](https://github.com/decadenza/SimpleStereo/blob/master/simplestereo/_rigs.py)  and the [documentation](https://decadenza.github.io/SimpleStereo/simplestereo.html#simplestereo._rigs.StereoRig), where you will find all the data you need. You can write a simple script to get the parameters from the rig object, e.g.:
```
# Load stereo rig from file
rigRect = ss.RectifiedStereoRig.fromFile(loadFile)

# The access the various items/methods.
rigRect.R # Rotation matrix
rigRect.T # Translation vector
rigRect.getBaseline()
rigRect.getFundamentalMatrix()
# And so on...
```

I need to double check all the fisheye-related stuff in the previous issue #25, before officially supporting it. So stay tuned...

Cheers
