### ISSUE TITLE
Short baseline calibration

### ISSUE THREAD

**Issue by KevinCain** [decadenza/SimpleStereo#29]
Here I calibrate a fixed stereo rig [using the images here](https://www.transfernow.net/dl/20231111Eh1hKyLg), calling SS with lightly edited versions of the SS canonical example scripts -- see /examples [in this branch of my SS fork](https://github.com/KevinCain/SimpleStereo/tree/HybridStereo):

```
X:\SimpleStereo\examples>python "003b BuildStereoRig.py"
Calibrating using 22 images from:
X:\data\chessboard_e\center_sync\center\...
X:\data\chessboard_e\center_sync\rgb\...
```
After calibration I rectify the rig and testing on images (included above):
```
X:\SimpleStereo\examples>python "005 RectifyRig.py"
X:\SimpleStereo\examples>python "006 RectifyImages.py"
```
The results are unusable -- which may very well be because the baseline between the two cameras is *very* short, ~2 cm. Are the results below consistent with that idea?

One undistorted frame via '004a UndistortImages.py'
![image](https://github.com/decadenza/SimpleStereo/assets/5424003/a0118504-3b7d-4ce0-97f7-d072eaed2260)

One rectified frame:
![image](https://github.com/decadenza/SimpleStereo/assets/5424003/8385430a-8b67-4775-a813-498051244b9b)

**Comment by decadenza** [comment]
Short baseline makes things more difficult. But the first problem I see is the number of calibration images.
22 is a very low number also in ideal conditions.

I normally use 200 couples of chessboard images. The chessboard must be of good quality and in focus. The corners must be sharp.

You may capture many more and at  post processing you may delete those images with poor quality.
