### ISSUE TITLE
Pipeline sequence for stereo rig rectification

### ISSUE THREAD

**Issue by KevinCain** [decadenza/SimpleStereo#3]
I see that in the supplied example code the `/home/kevin/SimpleStereo/examples/res/1/` path is consistently used for stereo rig calibration and rectification. That is, the example sequence for `res/1` appears to be as follows:
- 3: build a stereo rig from chessboard calibration
- 5: rectify the previously constructed rig
- 6: rectify a test stereo pair using the rectified rig above

This sequence skips the 4a/4b step of testing the calibration on a test image, as the source code shows that image distortion is handled prior to rectification, e.g. example 6.

Below are my steps, which yield good epipolar consistency but introduces telltale spherical distortion. Am I misinterpreting your intended sequence?

My steps are:

### Calibrate rig
Set ‘chessboardSize=(9,6)’ in `003 BuildStereoRig.py`, then:
`python 003\ BuildStereoRig.py`
### Rectify rig
`python 005\ RectifyRig.py`
### Test undistort
`python 004a\ UndistortImages.py`
This gives sane results shown below:
![image](https://user-images.githubusercontent.com/5424003/153508957-433f7e77-bf70-42a0-b3d2-481e078240d5.png)
### Rectify images
Copy ‘test_L.png’, ‘test_R.png’ to: `.../SimpleStereo/examples/res/1/`
Launch rectification with closed form [Direct Stereo Rectification](https://github.com/decadenza/DirectStereoRectification):
`python 006\ RectifyImages.py`
This yields the following (I added a few extra epipolar lines for clarity):
![image](https://user-images.githubusercontent.com/5424003/153510103-f5c8babc-aa99-46c7-875d-b1d03f2fa4bc.png)

**Comment by KevinCain** [comment]
For comparison, here I followed the above steps using a different set of (30) chessboard images. Where the last set attempted to maximize poses at different depths, this set uses similar depths but tries to pose the board towards frame corner points:

![image](https://user-images.githubusercontent.com/5424003/153524463-62552d9c-a8b4-445e-8b76-05f04d35fa48.png)

**Comment by decadenza** [comment]
Hello,
First thing was to test if the chessboards are detected correctly.

I used the following script on your images:
```
import numpy as np
import cv2
import glob

CHESSBOARDSIZE = (9,6)

if __name__ == "__main__": 
    # termination criteria
    criteria = (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 30, 1e-6)

    # prepare object points, like (0,0,0), (1,0,0), (2,0,0) ....,(6,5,0)
    objp = np.zeros((CHESSBOARDSIZE[0]*CHESSBOARDSIZE[1], 3), np.float32)
    objp[:,:2] = np.mgrid[0:CHESSBOARDSIZE[0],0:CHESSBOARDSIZE[1]].T.reshape(-1,2)

    # Arrays to store object points and image points from all the images.
    objpoints = [] # 3d point in real world space
    imgpoints = [] # 2d points in image plane.

    images = glob.glob('./1/calib/*.png')

    i=0
    for fname in images:
        img = cv2.imread(fname)
        gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)

        # Find the chess board corners
        ret, corners = cv2.findChessboardCorners(gray, CHESSBOARDSIZE)

        # If found, add object points, image points (after refining them)
        if ret == True:
            i+=1
            objpoints.append(objp)

            corners2 = cv2.cornerSubPix(gray,corners,(11,11),(-1,-1),criteria)
            imgpoints.append(corners2)
            print(i,'...')
            # Draw and display the corners
            img = cv2.drawChessboardCorners(img, CHESSBOARDSIZE, corners2,ret)
            cv2.imshow('img',img)
            cv2.waitKey(0)

    cv2.destroyAllWindows()
```
For example:
![chessboard](https://user-images.githubusercontent.com/30215028/153614753-e83f37f4-eb75-49a3-9fa2-a6aa2520e28a.png)

Everything appears ok. The chessboards are correctly detected in both setups. In fact the rectified images appear ok, if you ignore the surroundings.

Some scaling is automatically done by rectification algorithm. Rectification always comes with some degree of distortion too.

The camera distortion model is not perfect, in reality cameras do not follow it.
I usually calibrate a camera with more that 100 chessboard images. You should try to use more, so that the pinhole camera model can be better approximated.

Sometimes I notice that with cheap cameras, ignore distortion correction may be more effective.
You can try setting:
```
rig.distCoeffs1 = None
rig.distCoeffs2 = None
```
before using the rig for rectification.

Or if you use OpenCV directly, before calibration use `cv.stereoCalibrate()` with `CALIB_FIX_K1,...,CALIB_FIX_K6` and `CALIB_FIX_S1_S2_S3_S4` (all set to zero).

Hope this helps.

**Comment by KevinCain** [comment]
I've continued to test calibration, using fresh groups of images. As shown below, the reprojection error I see for (204) calibration images is nearly as high as for (30). The best results I have managed show ~0.5 pixels reprojection, with the rectification results shown below:
![im1](https://user-images.githubusercontent.com/5424003/153809643-27bf9191-3ac0-4e10-9fcb-31342994e866.png)
![im0](https://user-images.githubusercontent.com/5424003/153809638-e4cac8b9-8d90-4958-afe1-281e556ac978.png)

The distortion is clearly less than what I showed above in this thread, but still not usable. Setting the distortion coefficients to null before rectification as you suggested does help image completeness: 
![im1](https://user-images.githubusercontent.com/5424003/153810941-d919099f-c74f-4cc2-9462-cf0b6a8757c9.png)
![im0](https://user-images.githubusercontent.com/5424003/153810934-baeb8491-c18b-41e9-a781-446e6f1e3967.png)

Of course, in this case, the intrinsics for the stereo rig diverge from the scene geometry if we omit distortion terms, so onward use does poorly without including the distortion terms.

Since you show subpixel reprojection for your included chess board images, I suspect the trouble I'm having stems from the backlighted displays I am using to display the chess boards: I see the camera exposure leads to erosion at corner points, e.g.: 

<img width="211" alt="image" src="https://user-images.githubusercontent.com/5424003/153811775-ee2bf5ce-6ad9-4d17-94f8-12ba5a2023f8.png">

Does the erosion 'corner gap' above seem problematic? Have you seen trouble with on-screen calibration?

In the past I have used well made physical calibration boards (thick lucite with laminated prints). I'd like to cross-check with physical fiducials.

I see baseline values from ~81 to ~437 below, depending on the number of images in the calibration set:

> Calibrating using 204 images
> Reprojection error: 19.522355887333845
> Centers: (array([0., 0., 0.]), array([42.00022702,  2.53683576, 69.73632486]))
> Baseline: 81.44697422982081
> 
> Calibrating using 30 images
> Reprojection error: 31.016709893990758
> Centers: (array([0., 0., 0.]), array([194.61149018, 133.53586531, 367.45723149
> ]))
> Baseline: 436.7267754630001
> 
> Calibrating using 60 images
> /home/kevin/SimpleStereo/examples/res/1/calib...
> Saved in: /home/kevin/SimpleStereo/examples/res/1/rig.json
> Reprojection error: 23.031192039485756
> Centers: (array([0., 0., 0.]), array([ 98.53808355,  73.42140816, 311.64719174
> ]))
> Baseline: 334.9991480680074
> 
> Calibrating using 90 images
> /home/kevin/SimpleStereo/examples/res/1/calib...
> Saved in: /home/kevin/SimpleStereo/examples/res/1/rig.json
> Reprojection error: 28.98947354888402
> Centers: (array([0., 0., 0.]), array([112.14648405,  44.41719071, 849.6898556
> ]))
> Baseline: 858.2089322705364
> 
> Calibrating using 61 images
> Reprojection error: 0.5360569035508319
> Baseline: 59.883759250805255




> Calibrating using 204 images
> Reprojection error: 19.522355887333845
> Centers: (array([0., 0., 0.]), array([42.00022702,  2.53683576, 69.73632486]))
> Baseline: 81.44697422982081
> 
> Calibrating using 30 images
> Reprojection error: 31.016709893990758
> Centers: (array([0., 0., 0.]), array([194.61149018, 133.53586531, 367.45723149
> ]))
> Baseline: 436.7267754630001
> 
> Calibrating using 60 images
> /home/kevin/SimpleStereo/examples/res/1/calib...
> Saved in: /home/kevin/SimpleStereo/examples/res/1/rig.json
> Reprojection error: 23.031192039485756
> Centers: (array([0., 0., 0.]), array([ 98.53808355,  73.42140816, 311.64719174
> ]))
> Baseline: 334.9991480680074
> 
> Calibrating using 90 images
> /home/kevin/SimpleStereo/examples/res/1/calib...
> Saved in: /home/kevin/SimpleStereo/examples/res/1/rig.json
> Reprojection error: 28.98947354888402
> Centers: (array([0., 0., 0.]), array([112.14648405,  44.41719071, 849.6898556
> ]))
> Baseline: 858.2089322705364
> 
> Calibrating using 61 images
> Reprojection error: 0.5360569035508319
> Baseline: 59.883759250805255

**Comment by decadenza** [comment]
Thank you for your experiments. Personally I'd calibrate with a physical board.
Or you may [generate](https://github.com/decadenza/SimpleStereo/blob/47e597dfdbda25d657509e932fdb7533bff9f5ec/simplestereo/calibration.py#L978) and print a chessboard on paper and uniformly glue it to a board.

But... A stereo reprojection error of 0.5 is generally a quite good result!
As you pointed out, screen backlight may be a problem. After finding the corners, OpenCV uses a function (`cv2.cornerSubPix`) to refine the corner position.

I believe the images are rectified and undistorted correctly, just the distortion cannot be corrected in the extreme border areas.

I made a quick fix and updated the [example 006](https://github.com/decadenza/SimpleStereo/blob/master/examples/006%20RectifyImages.py)
You may try to uncomment the line:
`#rigRect.computeRectificationMaps(zoom=1.5) # May help removing unwanted border`
to add some zoom and discard the border.

**Comment by KevinCain** [comment]
@decadenza, to answer your question I used `006 RectifyImages.py` unmodified to produce the results above; naturally I swapped the provided data `examples\res\1` with my own.

Cropping the perimeter as in your updated [example 006](https://github.com/decadenza/SimpleStereo/blob/master/examples/006%20RectifyImages.py) is helpful, thanks. As you note, the undistortion and rectification steps unavoidably alter the source image, even moreso with the cheap 90^ lenses that I'm testing with.

I tested with a physical (printed) chess board; the reported reprojection error is a bit better, around ~0.4 pixels. Still not the ~0.1 range from the first data set, but a bit better. Below is a sample rectified pair using a 1.3 zoom value:
![im1](https://user-images.githubusercontent.com/5424003/153996726-5e8effa7-b9db-4be0-8941-8ab901dea333.png) ![im0](https://user-images.githubusercontent.com/5424003/153996735-2217d38a-2df1-438b-9fd3-2530e633b629.png)

The above uses your [Direct Stereo Rectification](https://github.com/decadenza/DirectStereoRectification) method. For comparison, here is the same input rectified with the OpenCV baseline method: 
![im1](https://user-images.githubusercontent.com/5424003/153996981-c8467834-77c4-42c4-b930-cc5b75cff1fa.png)
![im0](https://user-images.githubusercontent.com/5424003/153996987-37f30468-7360-4dfe-814b-9b61866f6bad.png)

**Comment by decadenza** [comment]
@KevinCain the images seem correctly rectified. I am glad that it works.
Please let me know if you are experiencing any other issues.
I am closing this.

_Side note_: `computeRectificationMaps` temporarily modifies the intrinsic camera matrices (these extra transformations are identified by `K1` and `K2` in the class `RectifiedStereoRig`. If you use the `RectifiedStereoRig.get3DPoints` to do triangulation, it will use the correct ones.  


Cheers
