### ISSUE TITLE
Unable to install on Ubuntu 22.04 jammy

### ISSUE THREAD

**Issue by andberto** [decadenza/SimpleStereo#34]
Hi i'm having problems installing the package
i'm using the same version of python 3.9.2 in a virtual enviroment with nothing installed and i get this error:

  /tmp/pip-build-env-8s150zg4/overlay/lib/python3.9/site-packages/setuptools/command/build_py.py:219: _Warning: Package simplestereo.headers'is absent from the `packages` configuration.
  ############################
  Package would be ignored
  ############################
  Python recognizes 'simplestereo.headers' as an importable package[^1],
  but it is absent from setuptools' `packages` configuration.

  This leads to an ambiguous overall configuration. If you want to distribute this
  package, please make sure that 'simplestereo.headers' is explicitly added
  to the `packages` configuration field.

  Alternatively, you can also rely on setuptools' discovery methods
  (for example by using `find_namespace_packages(...)`/`find_namespace:`
  instead of `find_packages(...)`/`find:`).

  You can read more about "package discovery" on setuptools documentation page:

  - https://setuptools.pypa.io/en/latest/userguide/package_discovery.html

  If you don't want 'simplestereo.headers' to be distributed and are
  already explicitly excluding 'simplestereo.headers' via
  `find_namespace_packages(...)/find_namespace` or `find_packages(...)/find`,
  you can try to use `exclude_package_data`, or `include-package-data=False` in
  combination with a more fine grained `package-data` configuration.

  You can read more about "package data files" on setuptools documentation page:

  - https://setuptools.pypa.io/en/latest/userguide/datafiles.html

  [^1]: For Python, any directory (with suitable naming) can be imported,
        even if it does not contain any `.py` files.
        On the other hand, currently there is no concept of package data
        directory, all directories are treated like packages.
  
And also this:
 
building 'simplestereo._passive' extension
creating build/temp.linux-x86_64-cpython-39/simplestereo
g++ -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/tmp/pip-build-env-8s150zg4/normal/lib/python3.9/site-packages/numpy/_core/include -I/home/berto/python_venvs/stereo/include -I/usr/local/include/python3.9 -c simplestereo/_passive.cpp -o build/temp.linux-x86_64-cpython-39/simplestereo/_passive.o -std=c++11 -DNDEBUG -DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION
g++ -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -shared build/temp.linux-x86_64-cpython-39/simplestereo/_passive.o -o build/lib.linux-x86_64-cpython-39/simplestereo/_passive.cpython-39-x86_64-linux-gnu.so -shared
building 'simplestereo._unwrapping' extension
g++ -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/tmp/pip-build-env-8s150zg4/normal/lib/python3.9/site-packages/numpy/_core/include -I/home/berto/python_venvs/stereo/include -I/usr/local/include/python3.9 -c simplestereo/_unwrapping.cpp -o build/temp.linux-x86_64-cpython-39/simplestereo/_unwrapping.o -std=c++11 -DNDEBUG -DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION
In file included from /tmp/pip-build-env-8s150zg4/normal/lib/python3.9/site-packages/numpy/_core/include/numpy/arrayobject.h:5,
                 from simplestereo/_unwrapping.cpp:5:
simplestereo/_unwrapping.cpp: In function ‘PyObject* infiniteImpulseResponse(PyObject*, PyObject*)’:
/tmp/pip-build-env-8s150zg4/normal/lib/python3.9/site-packages/numpy/_core/include/numpy/ndarrayobject.h:141:37: error: invalid conversion from ‘void*’ to ‘char*’ [-fpermissive]
  141 | #define PyArray_GETPTR2(obj, i, j) ((void *)(PyArray_BYTES(obj) + \
      |                                    ~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                     |
      |                                     void*
  142 |                                             (i)*PyArray_STRIDES(obj)[0] + \
      |                                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  143 |                                             (j)*PyArray_STRIDES(obj)[1]))
      |                                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
simplestereo/_unwrapping.cpp:112:36: note: in expansion of macro ‘PyArray_GETPTR2’
  112 |         PyArray_SETITEM(unwrapped, PyArray_GETPTR2(unwrapped,y,x), Py_BuildValue("f", (S>0)? temp/S : cur) );
      |                                    ^~~~~~~~~~~~~~~
In file included from /tmp/pip-build-env-8s150zg4/normal/lib/python3.9/site-packages/numpy/_core/include/numpy/arrayobject.h:5,
                 from simplestereo/_unwrapping.cpp:5:
/tmp/pip-build-env-8s150zg4/normal/lib/python3.9/site-packages/numpy/_core/include/numpy/ndarrayobject.h:292:43: note:   initializing argument 2 of ‘int PyArray_SETITEM(PyArrayObject*, char*, PyObject*)’
  292 | PyArray_SETITEM(PyArrayObject *arr, char *itemptr, PyObject *v)
      |                                     ~~~~~~^~~~~~~
In file included from /tmp/pip-build-env-8s150zg4/normal/lib/python3.9/site-packages/numpy/_core/include/numpy/arrayobject.h:5,
                 from simplestereo/_unwrapping.cpp:5:
/tmp/pip-build-env-8s150zg4/normal/lib/python3.9/site-packages/numpy/_core/include/numpy/ndarrayobject.h:141:37: error: invalid conversion from ‘void*’ to ‘char*’ [-fpermissive]
  141 | #define PyArray_GETPTR2(obj, i, j) ((void *)(PyArray_BYTES(obj) + \
      |                                    ~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                     |
      |                                     void*
  142 |                                             (i)*PyArray_STRIDES(obj)[0] + \
      |                                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  143 |                                             (j)*PyArray_STRIDES(obj)[1]))
      |                                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
simplestereo/_unwrapping.cpp:131:36: note: in expansion of macro ‘PyArray_GETPTR2’
  131 |         PyArray_SETITEM(unwrapped, PyArray_GETPTR2(unwrapped,y,x), Py_BuildValue("f", (S>0)? temp/S : cur) );
      |                                    ^~~~~~~~~~~~~~~
In file included from /tmp/pip-build-env-8s150zg4/normal/lib/python3.9/site-packages/numpy/_core/include/numpy/arrayobject.h:5,
                 from simplestereo/_unwrapping.cpp:5:
/tmp/pip-build-env-8s150zg4/normal/lib/python3.9/site-packages/numpy/_core/include/numpy/ndarrayobject.h:292:43: note:   initializing argument 2 of ‘int PyArray_SETITEM(PyArrayObject*, char*, PyObject*)’
  292 | PyArray_SETITEM(PyArrayObject *arr, char *itemptr, PyObject *v)
      |                                     ~~~~~~^~~~~~~
In file included from /tmp/pip-build-env-8s150zg4/normal/lib/python3.9/site-packages/numpy/_core/include/numpy/arrayobject.h:5,
                 from simplestereo/_unwrapping.cpp:5:
/tmp/pip-build-env-8s150zg4/normal/lib/python3.9/site-packages/numpy/_core/include/numpy/ndarrayobject.h:141:37: error: invalid conversion from ‘void*’ to ‘char*’ [-fpermissive]
  141 | #define PyArray_GETPTR2(obj, i, j) ((void *)(PyArray_BYTES(obj) + \
      |                                    ~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                     |
      |                                     void*
  142 |                                             (i)*PyArray_STRIDES(obj)[0] + \
      |                                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  143 |                                             (j)*PyArray_STRIDES(obj)[1]))
      |                                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
simplestereo/_unwrapping.cpp:151:40: note: in expansion of macro ‘PyArray_GETPTR2’
  151 |             PyArray_SETITEM(unwrapped, PyArray_GETPTR2(unwrapped,y,x), Py_BuildValue("f", (S>0)? temp/S : cur) );
      |                                        ^~~~~~~~~~~~~~~
In file included from /tmp/pip-build-env-8s150zg4/normal/lib/python3.9/site-packages/numpy/_core/include/numpy/arrayobject.h:5,
                 from simplestereo/_unwrapping.cpp:5:
/tmp/pip-build-env-8s150zg4/normal/lib/python3.9/site-packages/numpy/_core/include/numpy/ndarrayobject.h:292:43: note:   initializing argument 2 of ‘int PyArray_SETITEM(PyArrayObject*, char*, PyObject*)’
  292 | PyArray_SETITEM(PyArrayObject *arr, char *itemptr, PyObject *v)
      |                                     ~~~~~~^~~~~~~
error: command '/usr/bin/g++' failed with exit code 1

ERROR: Failed building wheel for SimpleStereo
Failed to build SimpleStereo
ERROR: Could not build wheels for SimpleStereo which use PEP 517 and cannot be installed directly

**Comment by decadenza** [comment]
Thank you for reporting this. It looks like they are related.
I'll try to fix it soon so you can try if it works on your machine.

**Comment by decadenza** [comment]
Currently on branch experimental. Please try to start a new venv, clone the repo and then:
```
git pull origin experimental
git checkout experimental
pip install .
```

Works for me. If it works for you too, happy to release to pip.

**Comment by decadenza** [comment]
Released a fix on PyPI as well. And tested on two different machines.
You should now be able to just run:
```
pip3 install simplestereo
```

I am closing this issue. Please reopen if necessary.
